name: Register Repository To Be Uploaded To Mirror
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'The name of the repository to mirror (not org name)'
        required: true
jobs:
  register-repo-with-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Initialize Repository
        run: echo "Hello World!" $GITHUB_REPOSITORY $GITHUB_REPOSITORY_OWNER "${{ github.workflow }}"
        
      - name: Register Repository With Weekly Mirror Workflow Repository
        run: |
          git status
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b '${{ github.event.inputs.repo }}'
          echo '${{ github.event.inputs.repo }}' >> repos_to_mirror.txt
          git add .
          git commit -m '[${{ github.workflow }}] Register repository to be mirrored (${{ github.event.inputs.repo }})'
          git push origin ${{ github.event.inputs.repo }}
          gh pr create -R $GITHUB_REPOSITORY --fill
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
